site_name: SaaS Architecture Review Navigator
site_url: https://kanaria007.github.io/saas-architecture-review-navigator/
repo_url: https://github.com/kanaria007/saas-architecture-review-navigator
repo_name: GitHub
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - tables
  - attr_list
  - md_in_html
plugins:
  - search
  - git-revision-date
nav:
  - Home: index.md
  - Navigation Map: navigation-map.md
  - Common:
      - "Design Justification": "categories/common/design-justification.md"
  - Domain:
      - "Domain Permissions": "categories/domain/domain-permissions.md"
      - "Domain Separation": "categories/domain/domain-separation.md"
      - "Domain Validation": "categories/domain/domain-validation.md"
      - "Inheritance Integrity": "categories/domain/inheritance-integrity.md"
      - "Invalid States": "categories/domain/invalid-states.md"
  - Data:
      - "Distributed Transaction Design": "categories/data/distributed-transaction-design.md"
      - "Fallback Strategy": "categories/data/fallback-strategy.md"
      - "Index Design": "categories/data/index-design.md"
      - "Indexing Strategy": "categories/data/indexing-strategy.md"
      - "Lifecycle Clarity": "categories/data/lifecycle-clarity.md"
      - "Migration Impact": "categories/data/migration-impact.md"
      - "Normalization Balance": "categories/data/normalization-balance.md"
      - "Retry Consistency": "categories/data/retry-consistency.md"
      - "Write Contention": "categories/data/write-contention.md"
  - API:
      - "API Compatibility Strategy": "categories/api/api-compatibility-strategy.md"
      - "API Permission Control": "categories/api/api-permission-control.md"
      - "API Schema Coherence": "categories/api/api-schema-coherence.md"
      - "Privilege Escalation Risk": "categories/api/privilege-escalation-risk.md"
      - "Sync vs Async Boundaries": "categories/api/sync-vs-async-boundaries.md"
  - Event:
      - "Cross-Service Consistency": "categories/async/cross-service-consistency.md"
      - "Event Retry Delay": "categories/async/event-retry-delay.md"
      - "External Failure Impact": "categories/async/external-failure-impact.md"
      - "Sync‑Async Alignment": "categories/async/sync-async-alignment.md"
  - Performance:
      - "API Response Latency": "categories/performance/api-response-latency.md"
      - "Backend Bottlenecks": "categories/performance/backend-bottlenecks.md"
      - "Cache Strategy": "categories/performance/cache-strategy.md"
      - "DB Index Optimization": "categories/performance/db-index-optimization.md"
      - "External Pressure Resilience": "categories/performance/external-pressure-resilience.md"
      - "Indexing Paths": "categories/performance/indexing-paths.md"
      - "Scaling Strategy": "categories/performance/scaling-strategy.md"
  - UI:
      - "Component Reuse Impact": "categories/ui/component-reuse-impact.md"
      - "Data Volume Visibility": "categories/ui/data-volume-visibility.md"
      - "Notification Localization": "categories/ui/notification-localization.md"
  - Test:
      - "Acceptance Criteria Definition": "categories/test/acceptance-criteria-definition.md"
      - "High‑Load Behavior Testing": "categories/test/high-load-behavior-testing.md"
      - "Impact Scope Analysis": "categories/test/impact-scope-analysis.md"
      - "Performance Test Plan": "categories/test/performance-test-plan.md"
  - Release:
      - "Impact Analysis for Critical Changes": "categories/release/impact-analysis-for-critical-changes.md"
      - "Minimize Downtime": "categories/release/minimize-downtime.md"
      - "Release Strategy Planning": "categories/release/release-strategy-planning.md"
      - "Rollback Strategy": "categories/release/rollback-strategy.md"
      - "Staged Release Strategy": "categories/release/staged-release-strategy.md"
      - "User Notification Preparation": "categories/release/user-notification-preparation.md"
  - Availability:
      - "Backup Strategy": "categories/availability/backup-strategy.md"
      - "Data Recovery Plan": "categories/availability/data-recovery-plan.md"
      - "Failover Design": "categories/availability/failover-design.md"
  - Non-Functional:
      - "Logging for Troubleshooting": "categories/non-functional/logging-for-troubleshooting.md"
      - "Observability & Alerting": "categories/non-functional/observability-alerting.md"
      - "Operational Burden": "categories/non-functional/operational-burden.md"
      - "Recovery Runbook": "categories/non-functional/recovery-runbook.md"
      - "Security Risks": "categories/non-functional/security-risks.md"
  - Security:
      - "AuthN/AuthZ Implementation": "categories/security/authn-authz-implementation.md"
      - "Confidential Data Handling": "categories/security/confidential-data-handling.md"