name: CI - Docs Static Check

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/**'
  push:
    branches:
      - main

jobs:
  build-and-check:
    name: Build Docs and Run Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-static-i18n

    - name: Install markdownlint
      run: |
        npm install -g markdownlint-cli

    - name: Run markdownlint
      run: |
        markdownlint docs/**/*.md

    - name: Validate structure
      run: python scripts/validate_structure.py

    - name: Build documentation
      run: mkdocs build --strict

    - name: Check for broken links
      uses: lycheeverse/lychee-action@v1.8.0
      with:
        args: --verbose --no-progress ./site/**/*.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
